/**
 * Generates src/data/embedded.ts — a baked-in snapshot of branches, catalog
 * (with per-branch stock) and reviews used by the standalone single-file
 * build, which runs with no backend. Run via `npm run gen:embedded`.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import type { Product } from '../src/types';
import { PRODUCTS, REVIEWS } from '../src/data/products';
import { BRANCH_SEED } from '../server/data/branches';

function hashStr(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function distribute(product: Product): Record<string, number> {
  if (product.branchStock) return product.branchStock;
  const dist: Record<string, number> = {};
  for (const b of BRANCH_SEED) dist[b.id] = 0;
  for (let unit = 0; unit < product.stock; unit++) {
    const idx = hashStr(`${product.id}:${unit}`) % BRANCH_SEED.length;
    dist[BRANCH_SEED[idx].id]++;
  }
  return dist;
}

const products = PRODUCTS.map((p) => ({ ...p, branchStock: distribute(p) }));

const out = `// AUTO-GENERATED by scripts/gen-embedded.ts — do not edit by hand.
// Snapshot of branches, catalog and reviews for the standalone (no-backend) build.
import type { Branch, Product, Review } from '../types';

export const EMBEDDED_BRANCHES: Branch[] = ${JSON.stringify(BRANCH_SEED, null, 2)};

export const EMBEDDED_PRODUCTS: Product[] = ${JSON.stringify(products, null, 2)};

export const EMBEDDED_REVIEWS: Review[] = ${JSON.stringify(REVIEWS, null, 2)};
`;

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, '..', 'src', 'data', 'embedded.ts');
writeFileSync(target, out);
console.log(`Wrote ${target} (${BRANCH_SEED.length} branches, ${products.length} products, ${REVIEWS.length} reviews).`);
